### ISSUE TITLE
Crash upon [add_new] clicking

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Rate#8]
When plus button is clicked, the app crashes sometimes.

**Comment by kirillt** [comment]
```
javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x78f3ef5888: I/O error during system call, Connection reset by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:256)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:202)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:155)
	at space.taran.arkrate.network.Crypto.getCryptoPrice(crypto.kt:33)
	at space.taran.arkrate.network.Crypto.getCryptoPriceWithCache(crypto.kt:57)
	at space.taran.arkrate.network.currencies.get(currencies.kt:185)
	at space.taran.arkrate.ui.MainActivityKt$Create$2$3$1$3$1$1$1.invoke(MainActivity.kt:117)
	at space.taran.arkrate.ui.MainActivityKt$Create$2$3$1$3$1$1$1.invoke(MainActivity.kt:115)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```
